### PR TITLE
Buffer share for github trending page.

### PR DESCRIPTION
**Pull request by vijayrawatsan**

### CODE REVIEW

**Comment by vijayrawatsan** [comment]
This is how it looks
screen shot 2015-07-31 at 1 01 52 pm

**Comment by vijayrawatsan** [comment]
Any update if you guys are gonna merge, review or close this :)

**Comment by pioul** [comment]
Hey Vijay, thanks for this nice PR and suggestion! We're going to ponder Buffer integration with GitHub soon, and if we decide to move forward with it, I'll be delighted to have a look at your PR! I'll let you know here in the comments how it went :smiley: Thanks again for the great suggestion!

**Comment by vijayrawatsan** [comment]
thanks @pioul

**Comment by pioul** [comment]
Hey @vijayrawatsan! Thanks again for your PR and proposed addition to the Buffer extension!

We've talked a bit about adding a Buffer button to GitHub, and the usual trade-off question for such integrations came up. Adding a new button to an external site means having to react super quickly to changes the external website might make to its pages' markup – otherwise the Buffer extension might end up breaking the page a bit. Since we're always striving to make the Buffer experience amazing for all our users, adding a new button means having to be on alert for a new external site in addition to the long list we already integrate with.

So, in the spirit of offering an awesome experience to all our users, we only want to add a Buffer button on an external site if that button is going to help a very large part of Buffer users. In the case of GitHub, we found that a lot of our users share projects and other pages from GitHub, but far less than what we deemed necessary for such an investment.

As a result, we won't be merging your PR just now – sorry about that! Maybe we'll come around to it later if new data suggests it would make the lives of even more Buffer users easier! Either way, your help with this proposition is *very* appreciated! :smiley: 

In the meantime, we're still very excited about understanding how you use Buffer with GitHub, and would like to learn what use-cases we could be solving for you and other Buffer users :smiley: 

One thing I'm wondering is what resources do you usually Buffer from GitHub? Whole projects, commits, maybe other pages?
I'm also curious about how you select what resources you're going to share from GitHub: do you usually navigate to a project and share one you've grown to like, or share new/trending projects that stand out as interesting, or anything else?

Again, thank you so much for the awesome PR, we're super grateful that you've taken the time to improve the extension like that! We're really looking forward to adding this in when it becomes clear that such a Buffer button on GitHub will benefit even more Buffer users! Thanks for your help! :smiley:

**Comment by vijayrawatsan** [comment]
Hi @pioul 
My use case is a simple one. I tend to follow trending repositories on github. When I like a repository I star it and buffer it. (And may be contribute if possible :wink: )

And I get your point, not a lot of your users would go to github trending page regularly to buffer repositories they like. 

Anyways, thanks for considering it. 
PS:
I think github changed their markup. PR is not working anymore. Will fix it for my self. :smile:

**Pull request closed without merging**
